### PR TITLE
Adds two more BubbleNips and border support

### PR DESCRIPTION
**Pull request by fischerscode**
This PR would add two more BubbleNips (`topRight` and `topLeft`) as well as support for borders as requested in #7.

### CODE REVIEW

**Comment by quentinleguennec** [comment]
I tested the border  on Android and I get this weird effect at the nip:
image

**Comment by fischerscode** [comment]
@quentinleguennec 
This should be fixed now.
Let me know if there is still an issue.

**Comment by quentinleguennec** [comment]
@fischerscode Thanks, that fixed it!

I went a checked all the other positions with a border and they all work except the new topLeft and topRight.
In fact those two give the same result as 'no' (no nip is drawn).

I tested by loading the previous commit (476ca605da989d53f55b5a3c32ea8e539099f392) and it's the same result so it's not a regression introduced with the new fix.

**Comment by fischerscode** [comment]
> In fact those two give the same result as 'no' (no nip is drawn).

Could you please send me a screenshot? In my test, everything seems to work.
simulator_screenshot_DFCADDC0-5F9F-4933-9AB7-171D1FEDC9B6

**Comment by quentinleguennec** [comment]
I just checked again and it's all working as expected.

The only way I can explain why is was not working for me previously is because I was trying to see if I could find a quick fix  by modifing the plugin code directly in the cached repo, and I did touch the code for those 2 nips. That was before trying your fix though, not sure why I would end up with the new code and still have some of my local changes at the same time,  wierd...

Anyway, it all works :)

**Comment by vi-k** [comment]
I apologize for disappearing.

Published 1.2.0. See [CHANGELOG](https://github.com/vi-k/bubble/blob/master/CHANGELOG.md).

I will try to add your wishes later.

**Comment by fischerscode** [comment]
I am closing this in favor of #40.

**Pull request closed without merging**
